# Generated by Django 4.0.4 on 2022-06-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientSide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='réservation',
            name='prix',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
