# Generated by Django 4.0.4 on 2022-06-13 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientSide', '0002_réservation_prix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='réservation',
            name='heure_début',
        ),
        migrations.RemoveField(
            model_name='réservation',
            name='heure_fin',
        ),
    ]
